#ifndef	ERROR_H
# define ERROR_H
# define ERROR_1 "Error\nNo .rt file\n"
# define ERROR_2 "Error\nTo many .rt files\n"
# define ERROR_3 "Error\nBad name for file\n"
# define ERROR_4 "Error\nOut of memmory for function get_tesk()!\n"
# define ERROE_5 "Error\nFailed to parce args!\n"
# define ERROR_6 "Error\nOut of memmory for function get_next_line()!\n"
# define ERROR_7 "Error\nOut of memmort for function ft_new_camera()!\n"
# define ERROR_8 "Error\nOut of memmory for function get_ray()!\n"
# define ERROR_9 "Error\nOut of memmory for function get_color()!\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
# define ERROR_ "Error\n"
#endif
